[package]
name = "ft60x_rs"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/NaluScientific/ft60x/"
authors = ["Mitchell Matsumori-Kelly <mitchell@naluscientific.com>"]
description = "Library for interfacing with FTDI FT60x USB 3.0 FIFO ICs via bindings to the D3XX library."

[dependencies]
thiserror = "1.0.38"
libc = "0.2.139"
libloading = "0.7.4"
once_cell = "1.17.1"
rust-embed = "6.8.1"
tempfile = "3.7.1"
dirs = "5.0.0"
